name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        env:
            TOKEN_FOR_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        run: npm ci

      - name: Build project
        env:
          TOKEN_FOR_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build

      - name: Deploy with Azure Static Web Apps CLI
        env:
          TOKEN_FOR_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        run: npx @azure/static-web-apps-cli deploy ./dist/ --deployment-token ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_DESERT_0ABC2E803 }} --env production

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_DESERT_0ABC2E803 }}
          action: "close"
